sudo: required
services:
  - docker

before_install:
  - docker build -t shengshengyang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shengshengyang/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  env: e-gahhcpdufj
  bucket: elasticbeanstalk-ap-southeast-1-491667161403
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY